require File.expand_path(File.dirname(__FILE__) + '/../../spec_helper')

packages =[
  'ansible',
  'autoconf',
  'automake',
  'awscli',
  'bash-git-prompt',
  'boost',
  'boot2docker',
  'brew-cask',
  'cairo',
  'chuck',
  'cloc',
  'collectd',
  'cscope',
  'csshx',
  'curl',
  'dirmngr',
  'docker',
  'dpkg',
  'exercism',
  'fontconfig',
  'freeimage',
  'freetype',
  'geoip',
  'gettext',
  'gh',
  'gibo',
  'git',
  'git-extras',
  'git-flow',
  'gitsh',
  'glib',
  'gmp',
  'gnu-tar',
  'gnupg',
  'gnupg2',
  'gnutls',
  'go',
  'gobject-introspection',
  'gpg-agent',
  'harfbuzz',
  'htop-osx',
  'hub',
  'icu4c',
  'imagemagick',
  'jpeg',
  'json-c',
  'json-glib',
  'keybase',
  'libassuan',
  'libevent',
  'libffi',
  'libgcrypt',
  'libgpg-error',
  'libiconv',
  'libidn',
  'libksba',
  'libpng',
  'librsync',
  'libtasn1',
  'libtiff',
  'libtool',
  'libusb',
  'libusb-compat',
  'libyaml',
  'links',
  'luajit',
  'macvim',
  'mysql',
  'nettle',
  'nmap',
  'node',
  'ntopng',
  'openssl',
  'p7zip',
  'packer',
  'pango',
  'passenger',
  'pcre',
  'pinentry',
  'pixman',
  'pkg-config',
  'popt',
  'pth',
  'pwgen',
  'qt',
  'rabbitmq',
  'rbenv',
  'rdiff-backup',
  'reaver',
  'redis',
  'rrdtool',
  'ruby-build',
  'skipfish',
  'surfraw',
  'sysdig',
  'tcpflow',
  'terraform',
  'the_silver_searcher',
  'tmate',
  'tree',
  'unrar',
  'wget',
  'xz',
  'youtube-dl',
  'zeromq'
  ]

services = [
  'homebrew.mxcl.collectd',
  'homebrew.mxcl.redis',
  'homebrew.mxcl.mysql',
  # 'homebrew.mxcl.boot2docker',
  # 'com.postgresapp.Postgres',
  'com.xwavesoft.pomodoromac',
  'org.openbsd.ssh-agent'
]

services.each do |s|
  describe service(s) do
    it { should be_running }
    it { should be_enabled }
  end
end

packages.each do |p|
  describe package(p), :if => os[:family] == 'darwin' do
    it { should be_installed }
  end
end
