---
galaxy_info:
  author: Sven Agnew
  description: Role to manage my workstation's ("Alderaan") installed packages
  company: Ideamachine
  # issue_tracker_url: http://example.com/issue/tracker
  license: Copyright (c) 2015 Sven Agnew. All Rights Reserved.
  min_ansible_version: 1.9
  platforms:
    - name: Ubuntu
      versions:
        - trusty
  categories:
    - development
    - packaging
    - system
dependencies: []
  # List your role dependencies here, one per line.
  # Be sure to remove the '[]' above if you add dependencies
  # to this list.
scm: git
version: 0.1
src: https://bitbucket.org/svenagnew/alderaan.git
